### ISSUE TITLE
IOException when querying table with a list<int> column.

### ISSUE THREAD

**Issue by daturkel** [duckdb/duckdb_iceberg#47]
Hello, thanks for your great work on duckdb-iceberg!

I'm encountering an issue where attempting to query an iceberg table with `iceberg_scan` fails if the table has a column which is a list of ints (`list<int>`). 

```python
table_with_lists # a pyiceberg.table.Table object
table_without_lists # another pyiceberg.table.Table object

duckdb.sql("INSTALL ICEBERG; LOAD ICEBERG;")

# querying the table that doesn't feature any lists works fine
duckdb.sql(f"SELECT * FROM iceberg_scan('{table_without_lists.metadata_location}') LIMIT 10")

# querying the table that *does* have lists throws an error
duckdb.sql(f"SELECT * FROM iceberg_scan('{table_with_lists.metadata_location}') LIMIT 10")
# IOException: IO Error: Invalid field found while parsing field: type
```

This seems to be related to an error [parsing the table schema](https://github.com/duckdb/duckdb_iceberg/blob/5a6b6e738f2009a09b92d948595a160955b826af/src/common/schema.cpp#L73-L81). I was wondering if there maybe was no logic for complex types in the duckdb-iceberg extension, but it appears that [there is](https://github.com/duckdb/duckdb_iceberg/blob/5a6b6e738f2009a09b92d948595a160955b826af/src/common/schema.cpp#L76-L77).

**Comment by samansmink** [comment]
Hey @daturkel!

There should be a workaround here https://github.com/duckdb/duckdb_iceberg/pull/45. It requires installing the nightly extension though!

**Comment by daturkel** [comment]
Thanks for the quick response! I tried the workaround suggested in that thread:

```python
duckdb.sql("force install iceberg from 'http://nightly-extensions.duckdb.org'")
duckdb.sql("load iceberg")
duckdb.sql(f"SELECT * FROM iceberg_scan('{metadata_location}') LIMIT 10")
```

but still got the IOException. This was the python duckdb 0.10.1 library.

**Comment by rustyconover** [comment]
I think I've addressed this with #50, it should fix parsing the metadata.

**Comment by jhump** [comment]
The issue is that DuckDB does not correctly interpret the schemas for list and map types.

The spec is here: https://iceberg.apache.org/spec/#schemas

The "element" field of a list type and the "key" and "value" fields of a map type are `<type JSON>`. A type in JSON is either a string for simple types or an object for composite types (structs, list, and maps). However, this implementation expects it to always be an object with a "type" attribute.

So the actual type for a list field will look like so:
```json
"type": {
  "type": "list",
  "element-id": 17,
  "element-required": true,
  "element": "long"
}
```
But this implementation instead requires it to look like so:
```json
"type": {
  "type": "list",
  "element-id": 17,
  "element-required": true,
  "element": {
    "type": "long"
  }
}
```
(The differences is in the "element" field.)

This is definitely a bug in this library that prevents it from working with any Iceberg table whose schema includes a list or map field.

**Comment by jhump** [comment]
@samansmink, I've created a pull request (#87) to address the issue described in the previous comment. Can you or some other DuckDB maintainer take a look?

**Comment by mheffner** [comment]
FWIW, this issue impacts querying of the new AWS S3 [Metadata tables](https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-s3-metadata-preview/). Adding `skip_schema_inference=True` allowed duckdb to query the table.

**Comment by psirenny** [comment]
I just discovered I need to set `skip_schema_inference=True` also. What are the consequences to disabling schema inference?
